version: '3.3'

services:

  evolutionapi:
    container_name: evolution-api
    image: atendai/evolution-api:v1.6.1
    restart: always
    volumes:
      - ./evolution-instances:/evolution/instances
      - ./evolution-store:/evolution/store
    env_file:
      - .env
    command: ['node', './dist/src/main.js']
    depends_on:
      - mongodb
    networks:
      - nginx
      - evolutionapi

  mongodb:
    container_name: mongodb-evolution
    image: mongo:5.0.24
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - PUID=1000
      - PGID=1000
    volumes:
      - ./mongodb-data:/data/db
      - ./mongodb-configdb:/data/configdb
    networks:
      - evolutionapi

  mongo-express:
    container_name: mongoexpress-evolution
    image: mongo-express:1.0.2-20
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: root
      ME_CONFIG_MONGODB_SERVER: mongodb-evolution
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    links:
      - mongodb
    networks:
      - nginx
      - evolutionapi

networks:
  nginx:
    external: true
  evolutionapi:
    external: true
